window.TEMPLATE_CATALOG = [
  {
    "name": "Sobre Dorado",
    "event": "Boda",
    "style": "Animada",
    "package": "Personalizado",
    "price": "Desde $90.000",
    "href": "../invitaciones-web-bodas/",
    "demoHref": "../plantillas/boda-juliana-pedro/",
    "preview": "preview--wedding",
    "thumb": "../assets/miniaturas/boda-juliana-pedro.webp"
  },
  {
    "name": "Elegante Floral",
    "event": "Boda",
    "style": "Animada",
    "package": "Personalizado",
    "price": "Desde $90.000",
    "href": "../invitaciones-web-bodas/",
    "demoHref": "../plantillas/boda-elegante-floral/",
    "preview": "preview--wedding",
    "thumb": "../assets/miniaturas/boda-elegante-floral.webp"
  },
  {
    "name": "Minimal Ivory",
    "event": "Boda",
    "style": "Animada",
    "package": "Personalizado",
    "price": "Desde $90.000",
    "href": "../invitaciones-web-bodas/",
    "demoHref": "../plantillas/boda-minimal-ivory/",
    "preview": "preview--wedding",
    "thumb": "../assets/miniaturas/boda-minimal-ivory.webp"
  },
  {
    "name": "Mesa y Galería",
    "event": "Boda",
    "style": "Animada",
    "package": "Premium",
    "price": "Desde $180.000",
    "href": "../invitaciones-web-bodas/",
    "demoHref": "../plantillas/boda-mesa-galeria/",
    "preview": "preview--wedding",
    "thumb": "../assets/miniaturas/boda-mesa-galeria.webp"
  },
  {
    "name": "Premium Olivo",
    "event": "Boda",
    "style": "Animada",
    "package": "Premium",
    "price": "Desde $180.000",
    "href": "../invitaciones-web-bodas/",
    "demoHref": "../plantillas/boda-premium-olivo/",
    "preview": "preview--wedding",
    "thumb": "../assets/miniaturas/boda-premium-olivo.webp"
  },
  {
    "name": "Premium Toile Azul",
    "event": "Boda",
    "style": "Animada",
    "package": "Premium",
    "price": "Desde $180.000",
    "href": "../invitaciones-web-bodas/",
    "demoHref": "../plantillas/boda-premium-toile/",
    "preview": "preview--wedding",
    "thumb": "../assets/miniaturas/boda-premium-toile.webp"
  },
  {
    "name": "Esmeralda y Lazo",
    "event": "Quinceanos",
    "style": "Animada",
    "package": "Personalizado",
    "price": "Desde $90.000",
    "href": "../invitaciones-web-quinceanos/",
    "demoHref": "../plantillas/quince-esmeralda/",
    "preview": "preview--wedding",
    "thumb": "../assets/miniaturas/quince-esmeralda.webp"
  },
  {
    "name": "Rosa Dorado",
    "event": "Quinceanos",
    "style": "Animada",
    "package": "Personalizado",
    "price": "Desde $90.000",
    "href": "../invitaciones-web-quinceanos/",
    "demoHref": "../plantillas/quince-rosa-dorado/",
    "preview": "preview--wedding",
    "thumb": "../assets/miniaturas/quince-rosa-dorado.webp"
  },
  {
    "name": "Noches de Gala",
    "event": "Quinceanos",
    "style": "Animada",
    "package": "Personalizado",
    "price": "Desde $90.000",
    "href": "../invitaciones-web-quinceanos/",
    "demoHref": "../plantillas/quince-noches-gala/",
    "preview": "preview--wedding",
    "thumb": "../assets/miniaturas/quince-noches-gala.webp"
  },
  {
    "name": "Mariposas Lila",
    "event": "Quinceanos",
    "style": "Animada",
    "package": "Personalizado",
    "price": "Desde $90.000",
    "href": "../invitaciones-web-quinceanos/",
    "demoHref": "../plantillas/quince-mariposas-lila/",
    "preview": "preview--wedding",
    "thumb": "../assets/miniaturas/quince-mariposas-lila.webp"
  },
  {
    "name": "Cristal Celeste",
    "event": "Quinceanos",
    "style": "Animada",
    "package": "Personalizado",
    "price": "Desde $90.000",
    "href": "../invitaciones-web-quinceanos/",
    "demoHref": "../plantillas/quince-cristal-celeste/",
    "preview": "preview--wedding",
    "thumb": "../assets/miniaturas/quince-cristal-celeste.webp"
  },
  {
    "name": "Azul Toile",
    "event": "Baby Shower",
    "style": "Animada",
    "package": "Personalizado",
    "price": "Desde $90.000",
    "href": "../invitaciones-baby-shower/",
    "demoHref": "../plantillas/baby-shower-thiago/",
    "preview": "preview--wedding",
    "thumb": "../assets/miniaturas/baby-shower-thiago.webp"
  },
  {
    "name": "Safari Suave",
    "event": "Baby Shower",
    "style": "Animada",
    "package": "Personalizado",
    "price": "Desde $90.000",
    "href": "../invitaciones-baby-shower/",
    "demoHref": "../plantillas/baby-safari-suave/",
    "preview": "preview--wedding",
    "thumb": "../assets/miniaturas/baby-safari-suave.webp"
  },
  {
    "name": "Osito Beige",
    "event": "Baby Shower",
    "style": "Animada",
    "package": "Personalizado",
    "price": "Desde $90.000",
    "href": "../invitaciones-baby-shower/",
    "demoHref": "../plantillas/baby-osito-beige/",
    "preview": "preview--wedding",
    "thumb": "../assets/miniaturas/baby-osito-beige.webp"
  },
  {
    "name": "Luna y Estrellas",
    "event": "Baby Shower",
    "style": "Animada",
    "package": "Personalizado",
    "price": "Desde $90.000",
    "href": "../invitaciones-baby-shower/",
    "demoHref": "../plantillas/baby-luna-estrellas/",
    "preview": "preview--wedding",
    "thumb": "../assets/miniaturas/baby-luna-estrellas.webp"
  },
  {
    "name": "Jardín Rosa",
    "event": "Baby Shower",
    "style": "Animada",
    "package": "Personalizado",
    "price": "Desde $90.000",
    "href": "../invitaciones-baby-shower/",
    "demoHref": "../plantillas/baby-jardin-rosa/",
    "preview": "preview--wedding",
    "thumb": "../assets/miniaturas/baby-jardin-rosa.webp"
  },
  {
    "name": "Dulce Revelación",
    "event": "Revelacion",
    "style": "Animada",
    "package": "Personalizado",
    "price": "Desde $90.000",
    "href": "../invitaciones-revelacion-genero/",
    "demoHref": "../plantillas/revelacion-dulce/",
    "preview": "preview--wedding",
    "thumb": "../assets/miniaturas/revelacion-dulce.webp"
  },
  {
    "name": "Ositos Team",
    "event": "Revelacion",
    "style": "Animada",
    "package": "Personalizado",
    "price": "Desde $90.000",
    "href": "../invitaciones-revelacion-genero/",
    "demoHref": "../plantillas/revelacion-ositos/",
    "preview": "preview--wedding",
    "thumb": "../assets/miniaturas/revelacion-ositos.webp"
  },
  {
    "name": "Globos al Viento",
    "event": "Revelacion",
    "style": "Animada",
    "package": "Personalizado",
    "price": "Desde $90.000",
    "href": "../invitaciones-revelacion-genero/",
    "demoHref": "../plantillas/revelacion-globos-aire/",
    "preview": "preview--wedding",
    "thumb": "../assets/miniaturas/revelacion-globos-aire.webp"
  },
  {
    "name": "Ropita Boho",
    "event": "Revelacion",
    "style": "Animada",
    "package": "Personalizado",
    "price": "Desde $90.000",
    "href": "../invitaciones-revelacion-genero/",
    "demoHref": "../plantillas/revelacion-ropita-boho/",
    "preview": "preview--wedding",
    "thumb": "../assets/miniaturas/revelacion-ropita-boho.webp"
  },
  {
    "name": "¿Qué será? Abejitas",
    "event": "Revelacion",
    "style": "Animada",
    "package": "Personalizado",
    "price": "Desde $90.000",
    "href": "../invitaciones-revelacion-genero/",
    "demoHref": "../plantillas/revelacion-abejitas/",
    "preview": "preview--wedding",
    "thumb": "../assets/miniaturas/revelacion-abejitas.webp"
  },
  {
    "name": "Clásico Suave",
    "event": "Bautizo",
    "style": "Animada",
    "package": "Personalizado",
    "price": "Desde $90.000",
    "href": "../invitaciones-bautizo/",
    "demoHref": "../plantillas/bautizo-clasico-suave/",
    "preview": "preview--wedding",
    "thumb": "../assets/miniaturas/bautizo-clasico-suave.webp"
  },
  {
    "name": "Capilla Blanca",
    "event": "Bautizo",
    "style": "Animada",
    "package": "Personalizado",
    "price": "Desde $90.000",
    "href": "../invitaciones-bautizo/",
    "demoHref": "../plantillas/bautizo-capilla-blanca/",
    "preview": "preview--wedding",
    "thumb": "../assets/miniaturas/bautizo-capilla-blanca.webp"
  },
  {
    "name": "Lazo de Perlas",
    "event": "Bautizo",
    "style": "Animada",
    "package": "Personalizado",
    "price": "Desde $90.000",
    "href": "../invitaciones-bautizo/",
    "demoHref": "../plantillas/bautizo-lazo-perlas/",
    "preview": "preview--wedding",
    "thumb": "../assets/miniaturas/bautizo-lazo-perlas.webp"
  },
  {
    "name": "Ovejita",
    "event": "Bautizo",
    "style": "Animada",
    "package": "Personalizado",
    "price": "Desde $90.000",
    "href": "../invitaciones-bautizo/",
    "demoHref": "../plantillas/bautizo-ovejita/",
    "preview": "preview--wedding",
    "thumb": "../assets/miniaturas/bautizo-ovejita.webp"
  },
  {
    "name": "Arco Celeste",
    "event": "Bautizo",
    "style": "Animada",
    "package": "Personalizado",
    "price": "Desde $90.000",
    "href": "../invitaciones-bautizo/",
    "demoHref": "../plantillas/bautizo-arco-celeste/",
    "preview": "preview--wedding",
    "thumb": "../assets/miniaturas/bautizo-arco-celeste.webp"
  },
  {
    "name": "Blanco Comunión",
    "event": "Primera Comunion",
    "style": "Animada",
    "package": "Personalizado",
    "price": "Desde $90.000",
    "href": "../invitaciones-primera-comunion/",
    "demoHref": "../plantillas/comunion-luz-dorada/",
    "preview": "preview--wedding",
    "thumb": "../assets/miniaturas/comunion-luz-dorada.webp"
  },
  {
    "name": "Niño Celeste",
    "event": "Primera Comunion",
    "style": "Animada",
    "package": "Personalizado",
    "price": "Desde $90.000",
    "href": "../invitaciones-primera-comunion/",
    "demoHref": "../plantillas/comunion-nino-celeste/",
    "preview": "preview--wedding",
    "thumb": "../assets/miniaturas/comunion-nino-celeste.webp"
  },
  {
    "name": "Arco Salvia",
    "event": "Primera Comunion",
    "style": "Animada",
    "package": "Personalizado",
    "price": "Desde $90.000",
    "href": "../invitaciones-primera-comunion/",
    "demoHref": "../plantillas/comunion-arco-salvia/",
    "preview": "preview--wedding",
    "thumb": "../assets/miniaturas/comunion-arco-salvia.webp"
  },
  {
    "name": "Paloma de Paz",
    "event": "Primera Comunion",
    "style": "Animada",
    "package": "Personalizado",
    "price": "Desde $90.000",
    "href": "../invitaciones-primera-comunion/",
    "demoHref": "../plantillas/comunion-paloma/",
    "preview": "preview--wedding",
    "thumb": "../assets/miniaturas/comunion-paloma.webp"
  },
  {
    "name": "Velo y Rosas",
    "event": "Primera Comunion",
    "style": "Animada",
    "package": "Personalizado",
    "price": "Desde $90.000",
    "href": "../invitaciones-primera-comunion/",
    "demoHref": "../plantillas/comunion-velo-rosas/",
    "preview": "preview--wedding",
    "thumb": "../assets/miniaturas/comunion-velo-rosas.webp"
  },
  {
    "name": "Lazo Vino",
    "event": "Cumpleanos",
    "style": "Animada",
    "package": "Personalizado",
    "price": "Desde $90.000",
    "href": "../invitaciones-cumpleanos/",
    "demoHref": "../plantillas/cumple-lazo-vino/",
    "preview": "preview--wedding",
    "thumb": "../assets/miniaturas/cumple-lazo-vino.webp"
  },
  {
    "name": "Coquette Rosa",
    "event": "Cumpleanos",
    "style": "Animada",
    "package": "Personalizado",
    "price": "Desde $90.000",
    "href": "../invitaciones-cumpleanos/",
    "demoHref": "../plantillas/cumple-coquette-rosa/",
    "preview": "preview--wedding",
    "thumb": "../assets/miniaturas/cumple-coquette-rosa.webp"
  },
  {
    "name": "Disco Glam",
    "event": "Cumpleanos",
    "style": "Animada",
    "package": "Personalizado",
    "price": "Desde $90.000",
    "href": "../invitaciones-cumpleanos/",
    "demoHref": "../plantillas/cumple-disco-glam/",
    "preview": "preview--wedding",
    "thumb": "../assets/miniaturas/cumple-disco-glam.webp"
  },
  {
    "name": "Globos Rosa",
    "event": "Cumpleanos",
    "style": "Animada",
    "package": "Personalizado",
    "price": "Desde $90.000",
    "href": "../invitaciones-cumpleanos/",
    "demoHref": "../plantillas/cumple-globos-rosa/",
    "preview": "preview--wedding",
    "thumb": "../assets/miniaturas/cumple-globos-rosa.webp"
  },
  {
    "name": "Princesa Rosa",
    "event": "Cumpleanos",
    "style": "Animada",
    "package": "Personalizado",
    "price": "Desde $90.000",
    "href": "../invitaciones-cumpleanos/",
    "demoHref": "../plantillas/cumple-princesa/",
    "preview": "preview--wedding",
    "thumb": "../assets/miniaturas/cumple-princesa.webp"
  },
  {
    "name": "Osito Aviador",
    "event": "Cumpleanos",
    "style": "Animada",
    "package": "Personalizado",
    "price": "Desde $90.000",
    "href": "../invitaciones-cumpleanos/",
    "demoHref": "../plantillas/cumple-osito-aviador/",
    "preview": "preview--wedding",
    "thumb": "../assets/miniaturas/cumple-osito-aviador.webp"
  }
];
