"""Configuracion de las plantillas de muestra (datos 100% ficticios)."""

CORM = "Cormorant+Garamond:ital,wght@0,400;0,500;0,600;0,700;1,500"


def claro(fondo_rgba):
    return f"linear-gradient(180deg,rgba(255,255,255,0) 48%,{fondo_rgba} 78%,{fondo_rgba} 100%)"


def oscuro(rgba):
    return f"linear-gradient(180deg,rgba(0,0,0,0) 40%,{rgba} 75%,{rgba} 100%)"


def tema(fondo, fondo2, tinta, titulo_color, acento, acento_texto, boton_texto, titulo, texto, portada_texto, velo,
         nombre_portada, nombre, tit, brillo, sombra="0 2px 12px rgba(0,0,0,.25)"):
    return {"fondo": fondo, "fondo2": fondo2, "tinta": tinta, "tinta-titulo": titulo_color, "acento": acento,
            "acento-texto": acento_texto, "boton-texto": boton_texto, "titulo": titulo, "texto": texto,
            "portada-texto": portada_texto, "velo": velo, "nombre-portada": nombre_portada, "nombre": nombre,
            "tit": tit, "brillo": brillo, "sombra-texto": sombra}


PLANTILLAS = [
    # ------------------------------ BODAS ------------------------------
    dict(slug="boda-elegante-floral", tarjeta="Elegante Floral", categoria="Boda", musica="boda-floral",
         imagen="https://img.recraft.ai/_067W9zPoGut-v_MoW9biufdz2sIlKlWTut3SyGPPRg/rs:fit:768:1344:0/raw:1/plain/abs://external/images/9db3f0b0-7c47-4b20-b35b-28964ee950e0",
         titulo="Nuestra boda · Isabella & Tomás", eti="Nos casamos", nombre="Isabella & Tomás", evento="nuestra boda",
         fechaISO="2027-02-20T16:00:00-05:00", fechaTexto="Sábado 20 de febrero", anioHora="2027 · 4:00 p. m.", fechaCorta="20 · 02 · 2027",
         lugar="Hacienda La Esperanza", direccion="Vía a Sáchica, km 3", ciudad="Villa de Leyva, Boyacá", titLugar="Ceremonia y recepción",
         frase="Con la bendición de Dios y nuestras familias, queremos compartir contigo el día en que unimos nuestras vidas.",
         itinerario=[("4:00 p. m.", "Ceremonia"), ("5:30 p. m.", "Cóctel"), ("7:00 p. m.", "Cena y fiesta")],
         vestir={"lineas": [("Código", "Formal de jardín"), ("Sugerencia", "Tonos tierra y pastel")], "colores": ["#e9c9c3", "#d8c3a5", "#b9c4ab", "#c9d3dd"]},
         regalo=("Lluvia de sobres", "Tu compañía es nuestro mejor regalo; si deseas tener un detalle, habrá un lugar para tu sobre."),
         nota="Con cariño, esta celebración es solo para adultos.", cierre="¡Te esperamos!",
         apertura="sobre", particulas="petalos", motivo="flor", colores=["#f3c9cf", "#fbe3e1", "#e8b4bc"], pista="Toca el sobre para abrir",
         fuentes=["Pinyon+Script", CORM],
         vars=tema("#fbf7f2", "#fdeee9", "#4a3b38", "#5b3a40", "#b76e79", "#8a4a55", "#fff", '"Pinyon Script",cursive', '"Cormorant Garamond",serif',
                   "#5b3a40", claro("rgba(251,247,242,.94)"), "54px", "58px", "40px", "#e8b4bc", "none")),

    dict(slug="boda-minimal-ivory", tarjeta="Minimal Ivory", categoria="Boda", musica="boda-ivory",
         imagen="https://img.recraft.ai/3JRs4u7BEBGPR-KKG-MzqXRJ17zuXolObAEk_WlFPYw/rs:fit:768:1344:0/raw:1/plain/abs://external/images/5814ce00-7bdb-40dc-b1f2-081a21c36cf6",
         titulo="Sara & Martín · Nuestra boda", eti="Nuestra boda", nombre="Sara & Martín", evento="nuestra boda",
         fechaISO="2027-04-10T17:00:00-05:00", fechaTexto="Sábado 10 de abril", anioHora="2027 · 5:00 p. m.", fechaCorta="10 · 04 · 27",
         lugar="Casa Museo del Puerto", direccion="Calle del Arsenal # 8-12", ciudad="Cartagena de Indias", titLugar="Celebración",
         frase="Menos es más. Solo faltas tú para que este día sea perfecto.",
         vestir={"lineas": [("Código", "Etiqueta"), ("Evita", "El blanco total")]},
         regalo=("Lista de regalos", "Tenemos una pequeña lista para empezar nuestro hogar. Pídenos el enlace por WhatsApp."),
         cierre="Gracias por ser parte", apertura="libro", particulas="estrellas", motivo="linea", pista="Toca para abrir",
         fuentes=["Italiana", "Jost:wght@400;500;600;700"],
         vars=tema("#f6f2ea", "#fbf8f2", "#2e2c29", "#2e2c29", "#a88b5c", "#86683a", "#fff", '"Italiana",serif', '"Jost",sans-serif',
                   "#2e2c29", claro("rgba(246,242,234,.93)"), "48px", "46px", "32px", "#cdb58a", "none")),

    dict(slug="boda-mesa-galeria", tarjeta="Mesa y Galería", categoria="Boda (Premium)", musica="boda-mesa",
         imagen="https://img.recraft.ai/6CE7yDinC35iyKxblRlhlzbTuLvsvHay5BFQn-edKdA/rs:fit:768:1344:0/raw:1/plain/abs://external/images/21cb67f0-6d9d-4873-aa4a-ab4a1c304486",
         titulo="Laura & Andrés · Boda", eti="Celebra con nosotros", nombre="Laura & Andrés", evento="nuestra boda",
         fechaISO="2027-06-05T18:00:00-05:00", fechaTexto="Sábado 5 de junio", anioHora="2027 · 6:00 p. m.", fechaCorta="05 · 06 · 2027",
         lugar="Finca El Encanto", direccion="Vereda Llanogrande", ciudad="Rionegro, Antioquia", titLugar="Recepción",
         frase="Una mesa larga, velas encendidas y la gente que más queremos. Así soñamos nuestra boda.",
         vestir={"lineas": [("Código", "Formal"), ("Tip", "Tacón ancho: ¡es en jardín!")]},
         regalo=("Lluvia de sobres", "Si deseas darnos un detalle, habrá un cofre especial en la recepción."),
         premium=True, nota="Invitación personal. Celebración para adultos.", cierre="¡Nos vemos en la mesa!",
         apertura="fotos", particulas="luciernagas", motivo="hoja", pista="Toca para abrir",
         fuentes=["Marcellus", "Allura"],
         vars=tema("#f3eee6", "#f9f3e8", "#2f2a24", "#3a2c1e", "#9c6b3c", "#7d5128", "#fff", '"Allura",cursive', '"Marcellus",serif',
                   "#fbeed8", oscuro("rgba(28,20,12,.86)"), "60px", "60px", "44px", "#ffd98a", "0 3px 16px rgba(0,0,0,.6)")),

    # ------------------------------ 15 AÑOS ------------------------------
    dict(slug="quince-rosa-dorado", tarjeta="Rosa Dorado", categoria="15 años", musica="quince-rosa",
         imagen="https://img.recraft.ai/WrceC0n832vIm68Y3i-xVm0vVuW8W2kIGdMRXQ0_ANI/rs:fit:768:1344:0/raw:1/plain/abs://external/images/4bf03986-e73f-44a2-b372-87a0b3b3af6e",
         titulo="Mis 15 años · Mariana", eti="Mis 15 años", nombre="Mariana", evento="mis 15 años",
         fechaISO="2027-01-23T19:00:00-05:00", fechaTexto="Sábado 23 de enero", anioHora="2027 · 7:00 p. m.", fechaCorta="23 · 01 · 2027",
         lugar="Club Campestre", direccion="Carrera 51B # 94-334", ciudad="Barranquilla, Atlántico",
         frase="Hay sueños que se cumplen con las personas que más quieres cerca. Acompáñame en esta noche mágica.",
         itinerario=[("7:00 p. m.", "Recepción"), ("8:00 p. m.", "Vals"), ("9:00 p. m.", "Cena y fiesta")],
         vestir={"lineas": [("Mujeres", "Vestido de gala"), ("Hombres", "Traje oscuro")], "colores": ["#e8a6b3"],
                 "nota": "El rosa está reservado para la quinceañera."},
         regalo=("Lluvia de sobres", "Tu presencia es mi mejor regalo; si deseas darme un detalle, habrá un lugar para tu sobre."),
         cierre="¡Te espero!", apertura="subir", particulas="petalos", motivo="corazon", colores=["#f7c1cc", "#fbd9df", "#eaa4b3"], pista="Toca para abrir",
         fuentes=["Parisienne", CORM],
         vars=tema("#fff6f6", "#ffe9ee", "#4a2f35", "#6d3444", "#c77d8c", "#9b4f5f", "#fff", '"Parisienne",cursive', '"Cormorant Garamond",serif',
                   "#fff", oscuro("rgba(120,52,72,.72)"), "64px", "60px", "40px", "#f7c1cc", "0 3px 14px rgba(90,20,40,.5)")),

    dict(slug="quince-noches-gala", tarjeta="Noches de Gala", categoria="15 años", musica="quince-gala",
         imagen="https://img.recraft.ai/WdgnyriwPpS3Hqohu3ME7SURVuu0kPUR5j1UoSKJl6M/rs:fit:768:1344:0/raw:1/plain/abs://external/images/7c3acd1d-e736-4ec8-bc86-63f5baa94d27",
         titulo="Noche de gala · Daniela XV", eti="Mis 15 años", nombre="Daniela", evento="mi noche de gala de 15 años",
         fechaISO="2027-05-15T20:00:00-05:00", fechaTexto="Sábado 15 de mayo", anioHora="2027 · 8:00 p. m.", fechaCorta="15 · 05 · 2027",
         lugar="Salón Gran Galeón", direccion="Anillo Vial, sector Cielo Mar", ciudad="Cartagena de Indias",
         frase="Una noche de estrellas, música y magia. Te invito a subir conmigo la escalera hacia mis 15.",
         vestir={"lineas": [("Código", "Gala / etiqueta"), ("Damas", "Vestido largo"), ("Caballeros", "Traje oscuro o esmoquin")], "colores": ["#1c2a57"],
                 "nota": "El azul noche está reservado para la quinceañera."},
         regalo=("Lluvia de sobres", "Tu presencia ilumina mi noche; si deseas darme un detalle, habrá un cofre para tu sobre."),
         nota="Esta noche la hemos pensado para compartir entre jóvenes y adultos. ¡Gracias por entenderlo!", cierre="¡Nos vemos en la gala!",
         apertura="cortina", particulas="estrellas", motivo="estrella", pista="Toca para abrir el telón",
         fuentes=[CORM, "Pinyon+Script"],
         vars=tema("#0d1426", "#1b2747", "#e9e4d8", "#f3e6c4", "#d4b26a", "#e3c47e", "#0d1426", '"Pinyon Script",cursive', '"Cormorant Garamond",serif',
                   "#f3e6c4", oscuro("rgba(8,12,28,.9)"), "66px", "62px", "40px", "#f3e6c4")),

    # ------------------------------ BABY SHOWER ------------------------------
    dict(slug="baby-safari-suave", tarjeta="Safari Suave", categoria="Baby shower", musica="baby-safari",
         imagen="https://img.recraft.ai/mtwf20Mwwu_RsOe7imG8Rd573x-dv3Qsa-lgVB9rKKc/rs:fit:768:1344:0/raw:1/plain/abs://external/images/c3c8fed4-9347-4dc5-8da4-4b17016c0647",
         titulo="Baby shower de Emiliano", eti="Baby shower", nombre="Emiliano", subnombre="viene en camino", evento="el baby shower de Emiliano",
         fechaISO="2027-03-06T15:00:00-05:00", fechaTexto="Sábado 6 de marzo", anioHora="2027 · 3:00 p. m.", fechaCorta="06 · 03 · 2027",
         lugar="Casa de los abuelos", direccion="Calle 29 # 12-40, barrio La Castellana", ciudad="Montería, Córdoba",
         frase="Una pequeña aventura está por comenzar. ¡Ven a celebrar con nosotros la llegada de Emiliano!",
         regalo=("Sugerencia de regalo", "Pañales etapa 2 o 3, o lo que nazca de tu corazón. 🍼"),
         confirmaTexto="Cuéntanos si vienes para preparar todo con amor.", cierre="¡Te esperamos!",
         apertura="persiana", particulas="burbujas", motivo="hoja", colores=["#b9c9a4", "#e3d3b5", "#c9dbe6"], pista="Toca para abrir",
         fuentes=["Fredoka:wght@400;500;600", "Nunito:ital,wght@0,400;0,600;0,700;1,400"],
         vars=tema("#f8f5ee", "#eef3e6", "#4b4a3f", "#4d5b3f", "#8fa37f", "#5e7250", "#fff", '"Fredoka",sans-serif', '"Nunito",sans-serif',
                   "#4d5b3f", claro("rgba(248,245,238,.95)"), "52px", "48px", "32px", "#b9c9a4", "none")),

    # ------------------------------ REVELACIÓN ------------------------------
    dict(slug="revelacion-dulce", tarjeta="Dulce Revelación", categoria="Revelación de género", musica="revelacion",
         imagen="https://img.recraft.ai/KY2Efm8wiy4Z92OBEvi8-esZ_SP8RCAz_oCn1GTB2yY/rs:fit:768:1344:0/raw:1/plain/abs://external/images/5c25c4da-f341-4eb1-b0c9-503a1bfc191b",
         titulo="¿Niño o niña? · Revelación", eti="Revelación de género", nombre="¿Niño o niña?", subnombre="Familia Rojas Díaz", evento="la revelación de nuestro bebé",
         fechaISO="2027-02-13T16:00:00-05:00", fechaTexto="Sábado 13 de febrero", anioHora="2027 · 4:00 p. m.", fechaCorta="13 · 02 · 2027",
         lugar="Salón Arcoíris", direccion="Carrera 25 # 23-50", ciudad="Sincelejo, Sucre",
         frase="Muy pronto sabremos si es él o ella. ¡Queremos que estés ahí cuando lo descubramos!",
         voto=True, vestir={"lineas": [("Juego", "Ven de azul si crees que es niño, de rosa si crees que es niña")], "colores": ["#8fb8e8", "#f2a7c3"]},
         regalo=("Sugerencia de regalo", "Pañales o ropita en tonos neutros. ¡Todo suma!"),
         cierre="¡Te esperamos!", apertura="rasca", rascaMsg="¡Estás invitado a descubrirlo!", particulas="confeti", motivo="corazon",
         colores=["#8fb8e8", "#f2a7c3", "#ffffff", "#c7b8ef"],
         fuentes=["Baloo+2:wght@400;600;700", "Dancing+Script:wght@600"],
         vars=tema("#f7f5fb", "#eaf1fb", "#454062", "#454062", "#8fb8e8", "#5b6fa8", "#fff", '"Dancing Script",cursive', '"Baloo 2",sans-serif',
                   "#454062", claro("rgba(247,245,251,.93)"), "54px", "52px", "38px", "#f2a7c3", "none")),

    # ------------------------------ BAUTIZO ------------------------------
    dict(slug="bautizo-clasico-suave", tarjeta="Clásico Suave", categoria="Bautizo", musica="bautizo-nubes",
         imagen="https://img.recraft.ai/43IfLKGnjjyKzv2T8OCHwLLFRnU3kfuZGI7Rv2zFdus/rs:fit:768:1344:0/raw:1/plain/abs://external/images/0727bc6c-3a2a-4978-bae7-14ba0f9ba0bf",
         titulo="Mi bautizo · Samuel", eti="Mi bautizo", nombre="Samuel", evento="mi bautizo",
         fechaISO="2027-01-30T10:00:00-05:00", fechaTexto="Sábado 30 de enero", anioHora="2027 · 10:00 a. m.", fechaCorta="30 · 01 · 2027",
         lugar="Parroquia San José", direccion="Calle 19 # 20-15", ciudad="Sincelejo, Sucre", titLugar="Ceremonia",
         lugar2=("Casa de la familia", "Calle 38 # 18-22, barrio Venecia", "Celebración"),
         padrinos=("Mis padrinos", "Carlos Pérez y Ana Gómez"),
         frase="Con la alegría de recibir a Dios en mi corazón, te invito a acompañarme en este día tan especial.",
         regalo=("Tu presencia", "Es mi mejor regalo. Si deseas tener un detalle, será recibido con mucho cariño."),
         cierre="¡Te espero!", apertura="nubes", particulas="estrellas", motivo="cruz", pista="Toca para abrir",
         fuentes=["Alex+Brush", CORM],
         vars=tema("#f4f8fb", "#e6eff7", "#33485a", "#33485a", "#7da2c1", "#4a7090", "#fff", '"Alex Brush",cursive', '"Cormorant Garamond",serif',
                   "#2f4a60", claro("rgba(244,248,251,.94)"), "64px", "62px", "42px", "#ffffff", "none")),

    dict(slug="bautizo-capilla-blanca", tarjeta="Capilla Blanca", categoria="Bautizo", musica="bautizo-capilla",
         imagen="https://img.recraft.ai/K1fhT000bA39t3dynpPKHR4_NRfTwx51QNNmOgjflKw/rs:fit:768:1344:0/raw:1/plain/abs://external/images/a62f3b54-0275-4f15-beab-e57ed92e5de1",
         titulo="Mi bautizo · Isabella", eti="Mi bautizo", nombre="Isabella", evento="mi bautizo",
         fechaISO="2027-03-20T11:00:00-05:00", fechaTexto="Sábado 20 de marzo", anioHora="2027 · 11:00 a. m.", fechaCorta="20 · 03 · 2027",
         lugar="Capilla Santa Bárbara", direccion="Calle de la Albarrada", ciudad="Santa Cruz de Mompox, Bolívar", titLugar="Ceremonia",
         lugar2=("Casa Amarilla", "Calle Real del Medio # 12-50", "Almuerzo familiar"),
         padrinos=("Mis padrinos", "Julián Martínez y Sofía Herrera"),
         frase="Las puertas de la capilla se abren para recibirme en la fe. Me encantaría que estés conmigo.",
         vestir={"lineas": [("Sugerencia", "Tonos pastel y claros")], "colores": ["#c9d6c0", "#f1d7d3", "#e9dfcc", "#cfdbe6"]},
         regalo=("Tu presencia", "Es mi mejor regalo. Si deseas tener un detalle, será recibido con mucho cariño."),
         cierre="¡Te espero!", apertura="puertas", particulas="petalos", motivo="cruz", colores=["#f1d7d3", "#e8c4c0", "#ffffff"], pista="Toca las puertas para abrir",
         fuentes=["Libre+Baskerville:ital@0;1", "Mrs+Saint+Delafield"],
         vars=tema("#fbfaf6", "#f1f3ec", "#3f433b", "#4c5a46", "#9aab8e", "#6b7d5f", "#fff", '"Mrs Saint Delafield",cursive', '"Libre Baskerville",serif',
                   "#4c5a46", claro("rgba(251,250,246,.95)"), "70px", "68px", "46px", "#e8c4c0", "none")),

    # ------------------------------ PRIMERA COMUNIÓN ------------------------------
    dict(slug="comunion-luz-dorada", tarjeta="Blanco Comunión", categoria="Primera comunión", musica="comunion",
         imagen="https://img.recraft.ai/kSmgPQ1ySd9yJYyPmAvCdhTsXBZlmdtOjK6wdkgS7Tw/rs:fit:768:1344:0/raw:1/plain/abs://external/images/2325e3b4-9ce7-4740-bef4-ac086d194830",
         titulo="Mi primera comunión · Valeria", eti="Mi primera comunión", nombre="Valeria", evento="mi primera comunión",
         fechaISO="2027-05-22T09:00:00-05:00", fechaTexto="Sábado 22 de mayo", anioHora="2027 · 9:00 a. m.", fechaCorta="22 · 05 · 2027",
         lugar="Parroquia Nuestra Señora del Carmen", direccion="Calle 27 # 5-10", ciudad="Montería, Córdoba", titLugar="Misa",
         lugar2=("Salón Los Almendros", "Carrera 6 # 60-12", "Celebración"),
         frase="«Dejad que los niños vengan a mí». Con alegría recibiré a Jesús por primera vez y quiero compartirlo contigo.",
         regalo=("Tu presencia", "Es mi mejor regalo. Si deseas tener un detalle, habrá un lugar para tu sobre."),
         cierre="¡Te espero!", apertura="resplandor", particulas="estrellas", motivo="cruz", pista="Toca para abrir",
         fuentes=["Tangerine:wght@400;700", "Lora:ital,wght@0,400;0,500;0,600;0,700;1,400"],
         vars=tema("#fcfaf5", "#fbf1dc", "#3d3528", "#5c4722", "#c29b4f", "#8d6c2c", "#fff", '"Tangerine",cursive', '"Lora",serif',
                   "#5c4722", claro("rgba(252,250,245,.95)"), "78px", "76px", "54px", "#e8c77a", "none")),

    # ------------------------------ CUMPLEAÑOS ------------------------------
    dict(slug="cumple-fiesta-globos", tarjeta="Fiesta Temática", categoria="Cumpleaños", musica="cumple-fiesta",
         imagen="https://img.recraft.ai/jWDO2CwvUISJoODpSfSSDnWirVzq9-1Cu4zXWK9OFAw/rs:fit:768:1344:0/raw:1/plain/abs://external/images/38744f81-1950-4c85-a4c6-1b734fb42236",
         titulo="¡Tomás cumple 8!", eti="¡Estás invitado!", nombre="Tomás", subnombre="cumple 8 años", evento="el cumpleaños de Tomás",
         fechaISO="2027-02-27T15:00:00-05:00", fechaTexto="Sábado 27 de febrero", anioHora="2027 · 3:00 p. m.", fechaCorta="27 · 02 · 2027",
         lugar="Salón Fiesta Mágica", direccion="Avenida Circunvalar # 40-18", ciudad="Montería, Córdoba",
         frase="¡Globos, torta, juegos y mucha diversión! Ven a celebrar conmigo un año más de aventuras.",
         itinerario=[("3:00 p. m.", "Juegos y show"), ("4:30 p. m.", "Piñata"), ("5:00 p. m.", "¡Torta!")],
         vestir={"lineas": [("Ropa", "Cómoda para jugar y saltar")]},
         regalo=("Regalos", "¡Tu presencia es el mejor regalo! 🎁"),
         confirmaTexto="Confírmale a mamá para guardarte tu sorpresa.", cierre="¡Te espero para jugar!",
         apertura="globo", particulas="confeti", motivo="globo", colores=["#ff6b5b", "#ffc93c", "#2ec4b6", "#9b5de5"], pista="Toca para reventar el globo",
         fuentes=["Lilita+One", "Nunito:ital,wght@0,400;0,600;0,700;1,400"],
         vars=tema("#fffaf3", "#fff0dc", "#2d2a4a", "#2d2a4a", "#ff6b5b", "#d84a3a", "#fff", '"Lilita One",sans-serif', '"Nunito",sans-serif',
                   "#2d2a4a", claro("rgba(255,250,243,.95)"), "58px", "54px", "34px", "#ffc93c", "none")),

    dict(slug="cumple-garden-party", tarjeta="Garden Party", categoria="Cumpleaños", musica="cumple-garden",
         imagen="https://img.recraft.ai/AI1-tJI7H2ogo80Rbhewa43nunhZ4eS7PVhh-V2-a7M/rs:fit:768:1344:0/raw:1/plain/abs://external/images/fb0caa6f-b545-4a89-a2b0-84848749bd8f",
         titulo="Garden party · Los 30 de Camila", eti="Garden party", nombre="Camila", subnombre="celebra sus 30", evento="los 30 de Camila",
         fechaISO="2027-04-24T16:00:00-05:00", fechaTexto="Sábado 24 de abril", anioHora="2027 · 4:00 p. m.", fechaCorta="24 · 04 · 2027",
         lugar="Casa Jardín", direccion="Vía al Rodadero, km 2", ciudad="Santa Marta, Magdalena",
         frase="Flores, limonada, buena música y mi gente favorita. Ven a celebrar mis 30 bajo los árboles.",
         vestir={"lineas": [("Código", "Casual elegante"), ("Tip", "Colores pastel y zapato cómodo para el césped")],
                 "colores": ["#f3c6a5", "#f6e3a1", "#c8d8b0", "#d9c7e3"]},
         regalo=("Regalos", "Lo que más quiero es verte ahí. Si deseas traer algo, ¡una planta será perfecta! 🌿"),
         cierre="¡Nos vemos en el jardín!", apertura="iris", particulas="luciernagas", motivo="flor", pista="Toca para abrir",
         fuentes=["DM+Serif+Display:ital@0;1", "Caveat:wght@500;700"],
         vars=tema("#f7f6ee", "#fbeedd", "#3f4a3a", "#3f4a3a", "#e39b73", "#b8683f", "#fff", '"Caveat",cursive', '"DM Serif Display",serif',
                   "#3f4a3a", claro("rgba(247,246,238,.95)"), "68px", "66px", "44px", "#f6d27a", "none")),
]
