"""Segunda tanda de plantillas de muestra (datos ficticios): cumpleaños, 15 años, baby shower, revelación, bautizo y comunión."""

CORM = "Cormorant+Garamond:ital,wght@0,400;0,500;0,600;0,700;1,500"
NUNITO = "Nunito:ital,wght@0,400;0,600;0,700;1,400"
QUICK = "Quicksand:wght@400;500;600;700"
R = "https://img.recraft.ai/"


def claro(c):
    return f"linear-gradient(180deg,rgba(255,255,255,0) 48%,{c} 78%,{c} 100%)"


def oscuro(c):
    return f"linear-gradient(180deg,rgba(0,0,0,0) 40%,{c} 75%,{c} 100%)"


def tema(fondo, fondo2, tinta, titulo_color, acento, acento_texto, titulo, texto, portada_texto, velo, np, n, t, brillo,
         boton_texto="#fff", sombra="none"):
    return {"fondo": fondo, "fondo2": fondo2, "tinta": tinta, "tinta-titulo": titulo_color, "acento": acento,
            "acento-texto": acento_texto, "boton-texto": boton_texto, "titulo": titulo, "texto": texto,
            "portada-texto": portada_texto, "velo": velo, "nombre-portada": np, "nombre": n, "tit": t, "brillo": brillo,
            "sombra-texto": sombra}


SOBRES = ("Lluvia de sobres", "Tu presencia es el mejor regalo; si deseas tener un detalle, habrá un lugar para tu sobre.")
PRESENCIA = ("Tu presencia", "Es mi mejor regalo. Si deseas tener un detalle, será recibido con mucho cariño.")
PANALES = ("Sugerencia de regalo", "Pañales etapa 1, 2 o 3, o lo que nazca de tu corazón. 🍼")


def base(**k):
    k.setdefault("evento", "mi celebración")
    return k


NUEVAS = [
    # ============================== CUMPLEAÑOS ==============================
    base(slug="cumple-lazo-vino", tarjeta="Lazo Vino", categoria="Cumpleaños", musica="cumple-vino", iconos="linea",
         imagen=R + "yhq-Ncj5HYKPl7D1u-bp3uJ2kLo6IyTBci3Djs9KPf0/rs:fit:768:1344:0/raw:1/plain/abs://external/images/a6206cc6-88a1-439c-ba60-a83653119f93",
         titulo="Natalia · 33", eti="Celebra conmigo", nombre="Natalia", subnombre="mis 33", evento="mi cumpleaños 33",
         fechaISO="2027-03-13T20:00:00-05:00", fechaTexto="Sábado 13 de marzo", anioHora="2027 · 8:00 p. m.", fechaCorta="13 · 03 · 2027",
         lugar="Terraza Alma", direccion="Calle del Curato # 38-12", ciudad="Cartagena de Indias",
         frase="Un año más, una copa más y las personas que más quiero. Brindemos juntos por mis 33.",
         vestir={"lineas": [("Código", "Elegante"), ("Tip", "Un toque de rojo vino")], "colores": ["#7b1e2b", "#e9e1d6", "#1c1c1c"]},
         regalo=SOBRES, cierre="¡Brindemos!", apertura="subir", particulas="estrellas", motivo="linea", pista="Toca para abrir",
         fuentes=["Monsieur+La+Doulaise", CORM],
         vars=tema("#f7f3ee", "#f3e6e3", "#3a2a2c", "#6e1a26", "#7b1e2b", "#7b1e2b", '"Monsieur La Doulaise",cursive', '"Cormorant Garamond",serif',
                   "#6e1a26", claro("rgba(247,243,238,.95)"), "76px", "74px", "50px", "#d9a5ad")),

    base(slug="cumple-coquette-rosa", tarjeta="Coquette Rosa", categoria="Cumpleaños", musica="coquette", iconos="suave",
         imagen=R + "3CasI8BVaJs-WmtipIaZFHqmaeNDqcYS4nIs7yHex7U/rs:fit:768:1344:0/raw:1/plain/abs://external/images/6180bbbc-f266-40d8-819c-b09e56361d37",
         titulo="Isabella cumple 20", eti="Happy birthday", nombre="Isabella", subnombre="mis 20 años", evento="mi cumpleaños",
         fechaISO="2027-02-20T18:00:00-05:00", fechaTexto="Sábado 20 de febrero", anioHora="2027 · 6:00 p. m.", fechaCorta="20 · 02 · 2027",
         lugar="Café Rosé", direccion="Carrera 43 # 80-15", ciudad="Barranquilla, Atlántico",
         frase="Lacitos, torta de corazón y mis personas favoritas. ¡Ven a celebrar mis 20 conmigo! 🎀",
         vestir={"lineas": [("Código", "Coquette"), ("Colores", "Rosa, blanco o crema")], "colores": ["#f4c6cf", "#ffffff", "#f3e5d6"]},
         regalo=("Regalos", "Tu presencia es lo más lindo que me puedes dar 💗"), cierre="¡Te espero!",
         apertura="iris", particulas="petalos", motivo="corazon", colores=["#f4c6cf", "#fbe0e5", "#ffffff"], pista="Toca para abrir",
         fuentes=["Corinthia:wght@400;700", "Lora:ital,wght@0,400;0,500;0,600;1,400"],
         vars=tema("#fcf8f2", "#fdebee", "#4d3439", "#9b4a5a", "#d88a9a", "#a4556a", '"Corinthia",cursive', '"Lora",serif',
                   "#9b4a5a", claro("rgba(252,248,242,.9)"), "78px", "76px", "54px", "#f4c6cf")),

    base(slug="cumple-disco-glam", tarjeta="Disco Glam", categoria="Cumpleaños", musica="cumple-disco", iconos="circulo",
         imagen=R + "tv2I8Gj5WcOM-FVfP7lMxgKnUkQ_Jn751b13QTaGSXQ/rs:fit:768:1344:0/raw:1/plain/abs://external/images/1c8f8ba3-057b-48ed-bcd9-3072e3980d6b",
         titulo="Adiós a los 20s · Estrella", eti="Good bye 20s", nombre="Estrella", subnombre="llega a los 30", evento="mi fiesta de 30",
         fechaISO="2027-05-29T21:00:00-05:00", fechaTexto="Sábado 29 de mayo", anioHora="2027 · 9:00 p. m.", fechaCorta="29 · 05 · 2027",
         lugar="Disco Club Mirage", direccion="Carrera 35 # 10-40", ciudad="Medellín, Antioquia",
         frase="Bola disco, brillo y la mejor música. ¡Despidamos mis 20s bailando hasta el amanecer! 🪩",
         vestir={"lineas": [("Código", "Brillos, plateado o negro"), ("Tip", "Zapatos cómodos para bailar")], "colores": ["#c9ccd3", "#111111", "#ffffff"]},
         regalo=("Regalos", "Solo trae tus mejores pasos de baile 💃"), nota="Fiesta para mayores de 18 años.", cierre="¡Nos vemos en la pista!",
         apertura="globo", particulas="estrellas", motivo="estrella", colores=["#e9ebf0", "#b7bcc6", "#ffffff", "#8a8f99"], pista="Toca para empezar la fiesta",
         fuentes=["Cinzel+Decorative:wght@400;700", "Montserrat:wght@400;500;600;700"],
         vars=tema("#0e0e10", "#1f2026", "#e7e7ea", "#ffffff", "#c9ccd3", "#dfe1e6", '"Cinzel Decorative",serif', '"Montserrat",sans-serif',
                   "#ffffff", oscuro("rgba(8,8,10,.92)"), "44px", "42px", "30px", "#ffffff", boton_texto="#111", sombra="0 2px 16px rgba(255,255,255,.35)")),

    base(slug="cumple-globos-rosa", tarjeta="Globos Rosa", categoria="Cumpleaños infantil", musica="cumple-fiesta", iconos="circulo",
         imagen=R + "sl3SgneIgCdCOvoH1c91stW65BgR4WM5sXzLuv_4x4s/rs:fit:768:1344:0/raw:1/plain/abs://external/images/df2bb189-0f6f-4a4c-8333-c488fc3daf3b",
         titulo="¡Mía cumple 6!", eti="¡Estás invitado!", nombre="Mía", subnombre="cumple 6 años", evento="el cumpleaños de Mía",
         fechaISO="2027-04-17T15:00:00-05:00", fechaTexto="Sábado 17 de abril", anioHora="2027 · 3:00 p. m.", fechaCorta="17 · 04 · 2027",
         lugar="Salón Burbujas", direccion="Calle 50 # 22-10", ciudad="Bucaramanga, Santander",
         frase="¡Globos, torta, música y muchos juegos! Ven a celebrar mis 6 años conmigo 🎈",
         itinerario=[("3:00 p. m.", "Juegos"), ("4:30 p. m.", "Piñata"), ("5:00 p. m.", "¡Torta!")],
         regalo=("Regalos", "¡Tu presencia es mi mejor regalo! 🎁"), confirmaTexto="Confírmale a mamá para guardarte tu sorpresa.", cierre="¡Te espero!",
         apertura="globo", particulas="confeti", motivo="globo", colores=["#f7a8c0", "#fcd3de", "#e98aa6", "#ffffff"], pista="Toca para reventar el globo",
         voladores=["globo-rosa", "mariposa"], fuentes=["Pacifico", NUNITO],
         vars=tema("#fff6f8", "#ffe6ee", "#5a2f3d", "#c04a74", "#e8779b", "#c04a74", '"Pacifico",cursive', '"Nunito",sans-serif',
                   "#c04a74", claro("rgba(255,242,246,.94)"), "58px", "56px", "36px", "#f7a8c0")),

    base(slug="cumple-princesa", tarjeta="Princesa Rosa", categoria="Cumpleaños infantil", musica="princesa", iconos="arco",
         imagen=R + "6c3Rso2tahss6KcXuC3fbGWE4wzxCmsvDGQ7U3uXmpA/rs:fit:768:1344:0/raw:1/plain/abs://external/images/2b1befe1-289e-4c6c-9958-d40fef55e973",
         titulo="Emma · Mi primer añito", eti="Mi primer añito", nombre="Emma", subnombre="cumple 1 año", evento="el primer añito de Emma",
         fechaISO="2027-03-27T16:00:00-05:00", fechaTexto="Sábado 27 de marzo", anioHora="2027 · 4:00 p. m.", fechaCorta="27 · 03 · 2027",
         lugar="Jardín de los Sueños", direccion="Vía Chía-Cajicá, km 2", ciudad="Chía, Cundinamarca",
         frase="Había una vez una princesa que cumplía su primer año… ¡y quiere celebrarlo contigo en su castillo! 👑",
         regalo=("Regalos", "Tu cariño es el regalo más bonito para mi primer añito."), cierre="¡Te espero en mi castillo!",
         apertura="puertas", particulas="estrellas", motivo="corazon", pista="Toca para abrir el castillo",
         voladores=["mariposa"], fuentes=["Petit+Formal+Script", QUICK],
         vars=tema("#fdf8f4", "#fbeaea", "#5a3f3f", "#a8606a", "#d59aa0", "#a8606a", '"Petit Formal Script",cursive', '"Quicksand",sans-serif',
                   "#a8606a", claro("rgba(253,248,244,.95)"), "52px", "50px", "34px", "#e8c07a")),

    base(slug="cumple-osito-aviador", tarjeta="Osito Aviador", categoria="Cumpleaños infantil", musica="baby-safari", iconos="suave",
         imagen=R + "VZFRu9pbJLPTNTOtG1-EiCyMRqzLIm2t1NG-OuiCEYs/rs:fit:768:1344:0/raw:1/plain/abs://external/images/5d69d6d3-769c-4c88-8696-6e8cc320c193",
         titulo="Matías · Mi primer añito", eti="Mi primera aventura", nombre="Matías", subnombre="cumple 1 año", evento="el primer añito de Matías",
         fechaISO="2027-05-08T15:00:00-05:00", fechaTexto="Sábado 8 de mayo", anioHora="2027 · 3:00 p. m.", fechaCorta="08 · 05 · 2027",
         lugar="Casa Campestre Los Pinos", direccion="Vereda El Retiro", ciudad="Rionegro, Antioquia",
         frase="¡Despegamos! Mi primer año de aventuras merece una gran celebración a bordo de mi globo ✈️",
         regalo=("Regalos", "Tu compañía es el mejor regalo para mi primer añito."), cierre="¡Te espero a bordo!",
         apertura="nubes", particulas="estrellas", motivo="estrella", pista="Toca para despegar",
         voladores=["avion", "globo-azul"], fuentes=["Sniglet:wght@400;800", NUNITO],
         vars=tema("#f8f6f1", "#e9eef4", "#3f4652", "#3f5a78", "#8aa6c1", "#51708f", '"Sniglet",sans-serif', '"Nunito",sans-serif',
                   "#3f5a78", claro("rgba(248,246,241,.95)"), "54px", "50px", "32px", "#d8c3a0")),

    # ============================== 15 AÑOS ==============================
    base(slug="quince-mariposas-lila", tarjeta="Mariposas Lila", categoria="15 años", musica="quince-rosa", iconos="rombo",
         imagen=R + "0_QwNwEg0WfmWgIopb-JB5BRv0Jw894gX8ouxzuL0-Y/rs:fit:768:1344:0/raw:1/plain/abs://external/images/bbc0675d-d1bb-42cb-a131-94143761022d",
         titulo="Mis 15 años · Luciana", eti="Mis 15 años", nombre="Luciana", evento="mis 15 años",
         fechaISO="2027-07-10T19:00:00-05:00", fechaTexto="Sábado 10 de julio", anioHora="2027 · 7:00 p. m.", fechaCorta="10 · 07 · 2027",
         lugar="Salón Lavanda", direccion="Avenida Pedro de Heredia # 31-50", ciudad="Cartagena de Indias",
         frase="Como una mariposa, hoy abro mis alas a una nueva etapa. Me encantaría que vueles conmigo.",
         itinerario=[("7:00 p. m.", "Recepción"), ("8:00 p. m.", "Vals"), ("9:00 p. m.", "Fiesta")],
         vestir={"lineas": [("Damas", "Vestido largo"), ("Caballeros", "Traje formal")], "colores": ["#b89bd6"], "nota": "El lila está reservado para la quinceañera."},
         regalo=SOBRES, cierre="¡Te espero!", apertura="persiana", particulas="estrellas", motivo="flor", pista="Toca para abrir",
         fuentes=["Style+Script", CORM],
         vars=tema("#f8f5fb", "#efe6f8", "#3e3350", "#5e3f86", "#9b7cc4", "#6f4f9b", '"Style Script",cursive', '"Cormorant Garamond",serif',
                   "#5e3f86", claro("rgba(245,240,251,.94)"), "72px", "70px", "48px", "#d8c8ef")),

    base(slug="quince-cristal-celeste", tarjeta="Cristal Celeste", categoria="15 años", musica="quince-gala", iconos="rombo",
         imagen=R + "rJMTW909cszBvP1XvI6kSTGk6-P3l-qtpo8wmUujtJU/rs:fit:768:1344:0/raw:1/plain/abs://external/images/5cb29dfd-c828-4834-953b-122ac408ac3a",
         titulo="Mis 15 años · Antonella", eti="Mis 15 años", nombre="Antonella", evento="mis 15 años",
         fechaISO="2027-08-21T20:00:00-05:00", fechaTexto="Sábado 21 de agosto", anioHora="2027 · 8:00 p. m.", fechaCorta="21 · 08 · 2027",
         lugar="Hotel Cristal", direccion="Carrera 2 # 5-20, El Laguito", ciudad="Cartagena de Indias",
         frase="A la medianoche la magia no termina: apenas comienza. Acompáñame en mi noche de cuento de hadas.",
         vestir={"lineas": [("Código", "Gala"), ("Damas", "Vestido largo"), ("Caballeros", "Traje oscuro")], "colores": ["#a9c6e3"],
                 "nota": "El azul celeste está reservado para la quinceañera."},
         regalo=SOBRES, cierre="¡Te espero en mi noche mágica!", apertura="resplandor", particulas="estrellas", motivo="estrella", pista="Toca para abrir",
         fuentes=["Sacramento", CORM],
         vars=tema("#f5f9fc", "#e3eef8", "#2d3d52", "#355a82", "#7fa3c9", "#456d98", '"Sacramento",cursive', '"Cormorant Garamond",serif',
                   "#355a82", claro("rgba(240,246,252,.93)"), "74px", "70px", "48px", "#dfe9f5")),

    # ============================== BABY SHOWER ==============================
    base(slug="baby-osito-beige", tarjeta="Osito Beige", categoria="Baby shower", musica="baby-safari", iconos="suave",
         imagen=R + "T_SSW9KAeZJb1e8gh9hZB9Ni8f4T_MXnugOIe2DY1go/rs:fit:768:1344:0/raw:1/plain/abs://external/images/c76a007c-4b47-4400-b4c7-4dc6849fbf0d",
         titulo="Baby shower de Lucas", eti="Baby shower", nombre="Lucas", subnombre="viene en camino", evento="el baby shower de Lucas",
         fechaISO="2027-02-06T15:00:00-05:00", fechaTexto="Sábado 6 de febrero", anioHora="2027 · 3:00 p. m.", fechaCorta="06 · 02 · 2027",
         lugar="Casa de la familia", direccion="Calle 10 # 5-30, barrio El Prado", ciudad="Valledupar, Cesar",
         frase="Un pequeño osito está por llegar y queremos celebrarlo con las personas que más queremos 🧸",
         regalo=PANALES, cierre="¡Te esperamos!", apertura="subir", particulas="estrellas", motivo="estrella", pista="Toca para abrir",
         voladores=["globo-azul", "globo-rosa"], fuentes=["Comfortaa:wght@400;600;700", NUNITO],
         vars=tema("#faf7f2", "#f1ebe1", "#4c4238", "#6b5543", "#b59b7f", "#86684c", '"Comfortaa",sans-serif', '"Nunito",sans-serif',
                   "#6b5543", claro("rgba(250,247,242,.95)"), "50px", "46px", "30px", "#e2cfb2")),

    base(slug="baby-luna-estrellas", tarjeta="Luna y Estrellas", categoria="Baby shower", musica="luna", iconos="arco",
         imagen=R + "ghZM6nkAHQYx9dYDXqNf7Zn5fg6dGcGtOgO-m0XRH1A/rs:fit:768:1344:0/raw:1/plain/abs://external/images/1e05ce20-68b0-4ce8-99e8-ff927471be94",
         titulo="Baby shower de Martín", eti="Baby shower", nombre="Martín", subnombre="nuestra estrellita", evento="el baby shower de Martín",
         fechaISO="2027-03-20T16:00:00-05:00", fechaTexto="Sábado 20 de marzo", anioHora="2027 · 4:00 p. m.", fechaCorta="20 · 03 · 2027",
         lugar="Salón Luna Azul", direccion="Carrera 7 # 22-18", ciudad="Pereira, Risaralda",
         frase="Brilla, brilla, estrellita… Muy pronto llega Martín y queremos celebrarlo contigo ⭐",
         regalo=PANALES, cierre="¡Te esperamos!", apertura="iris", particulas="estrellas", motivo="estrella", pista="Toca para abrir",
         voladores=["avion", "globo-azul"], fuentes=["Cookie", NUNITO],
         vars=tema("#f6f8fb", "#e4ecf5", "#35415a", "#3c5a85", "#7d9cc4", "#4d6f9f", '"Cookie",cursive', '"Nunito",sans-serif',
                   "#3c5a85", claro("rgba(246,248,251,.95)"), "66px", "62px", "44px", "#e9d59a")),

    base(slug="baby-jardin-rosa", tarjeta="Jardín Rosa", categoria="Baby shower", musica="coquette", iconos="suave",
         imagen=R + "NPe5w9yJzxETJehO6ime2vDChQ-L-Ikx8usjA0B7v20/rs:fit:768:1344:0/raw:1/plain/abs://external/images/6523b313-ef77-48c2-ac24-697252734949",
         titulo="Baby shower de Valentina", eti="Baby shower", nombre="Valentina", subnombre="nuestra florecita", evento="el baby shower de Valentina",
         fechaISO="2027-04-10T15:00:00-05:00", fechaTexto="Sábado 10 de abril", anioHora="2027 · 3:00 p. m.", fechaCorta="10 · 04 · 2027",
         lugar="Jardín Las Peonías", direccion="Calle 5 # 38-40", ciudad="Cali, Valle del Cauca",
         frase="Entre flores y mucho amor esperamos a nuestra niña. ¡Ven a celebrar su llegada! 🌸",
         regalo=PANALES, cierre="¡Te esperamos!", apertura="libro", particulas="petalos", motivo="flor", colores=["#f6cdd3", "#fbe4e6", "#ffffff"], pista="Toca para abrir",
         voladores=["mariposa"], fuentes=["Great+Vibes", QUICK],
         vars=tema("#fdf9f6", "#fcecec", "#56403f", "#b05d6b", "#dd9aa5", "#b05d6b", '"Great Vibes",cursive', '"Quicksand",sans-serif',
                   "#b05d6b", claro("rgba(253,249,246,.95)"), "68px", "64px", "44px", "#f6cdd3")),

    # ============================== REVELACIÓN ==============================
    base(slug="revelacion-ositos", tarjeta="Ositos Team", categoria="Revelación de género", musica="revelacion", iconos="circulo",
         imagen=R + "STotiF2R-2sG2eWWUixD0XFI9_7q7IscSZRSh3nrvtc/rs:fit:768:1344:0/raw:1/plain/abs://external/images/9fc50e3b-48b8-4f85-bf02-a769f3357eb7",
         titulo="¿Niño o niña? · Familia Torres", eti="Revelación de género", nombre="¿Niño o niña?", subnombre="Familia Torres Ruiz", evento="la revelación de nuestro bebé",
         fechaISO="2027-03-06T16:00:00-05:00", fechaTexto="Sábado 6 de marzo", anioHora="2027 · 4:00 p. m.", fechaCorta="06 · 03 · 2027",
         lugar="Casa Torres", direccion="Calle 15 # 9-40", ciudad="Montería, Córdoba",
         frase="¿Osito azul u osita rosa? ¡Ven a descubrirlo con nosotros!", voto=True,
         vestir={"lineas": [("Team niño", "Ven de azul"), ("Team niña", "Ven de rosa")], "colores": ["#8fb2d9", "#eea7b9"]},
         regalo=PANALES, cierre="¡Te esperamos!", apertura="horizontal", particulas="confeti", motivo="corazon", colores=["#8fb2d9", "#eea7b9", "#e8dcc8"], pista="Toca para abrir",
         voladores=["globo-azul", "globo-rosa"], fuentes=["Fredoka:wght@400;500;600", "Dancing+Script:wght@600"],
         vars=tema("#fbf8f3", "#f1ece4", "#4a3f3a", "#5e4a3d", "#b8977a", "#7f6048", '"Fredoka",sans-serif', '"Dancing Script",cursive',
                   "#5e4a3d", claro("rgba(251,248,243,.95)"), "46px", "42px", "30px", "#eea7b9")),

    base(slug="revelacion-globos-aire", tarjeta="Globos al Viento", categoria="Revelación de género", musica="luna", iconos="suave",
         imagen=R + "X5pZ6M9-kpyljpGKiWETE4H3T40hSmwmBQULRipLLok/rs:fit:768:1344:0/raw:1/plain/abs://external/images/8b6fe940-60c0-4949-8991-1a4f188cd4f9",
         titulo="¿Él o ella? · Revelación", eti="Revelación de género", nombre="¿Él o ella?", subnombre="Familia Castro Peña", evento="la revelación de nuestro bebé",
         fechaISO="2027-04-24T16:00:00-05:00", fechaTexto="Sábado 24 de abril", anioHora="2027 · 4:00 p. m.", fechaCorta="24 · 04 · 2027",
         lugar="Finca El Mirador", direccion="Vía a Santa Elena, km 4", ciudad="Medellín, Antioquia",
         frase="Nuestro globo más especial está por despegar. ¡Acompáñanos a descubrir si es niño o niña!", voto=True,
         regalo=PANALES, cierre="¡Te esperamos!", apertura="nubes", particulas="estrellas", motivo="globo", pista="Toca para abrir",
         voladores=["globo-azul", "globo-rosa"], fuentes=["Sacramento", QUICK],
         vars=tema("#fbf8f5", "#eef1f7", "#43465a", "#4f5d85", "#9aa9cc", "#5d6d9a", '"Sacramento",cursive', '"Quicksand",sans-serif',
                   "#4f5d85", claro("rgba(251,248,245,.95)"), "64px", "60px", "44px", "#f0b9c8")),

    base(slug="revelacion-ropita-boho", tarjeta="Ropita Boho", categoria="Revelación de género", musica="baby-safari", iconos="arco",
         imagen=R + "aMawdC_5xqOF1gC3hfR5hvrqhlH1vmM-T2tnUgU01mg/rs:fit:768:1344:0/raw:1/plain/abs://external/images/8ce17b1c-5ced-433f-95e8-824f728b5251",
         titulo="¿Niño o niña? · Boho", eti="Revelación de género", nombre="¿Niño o niña?", subnombre="Familia Vargas Gil", evento="la revelación de nuestro bebé",
         fechaISO="2027-05-15T15:00:00-05:00", fechaTexto="Sábado 15 de mayo", anioHora="2027 · 3:00 p. m.", fechaCorta="15 · 05 · 2027",
         lugar="Casa de campo Los Almendros", direccion="Vía Turbaco, km 3", ciudad="Turbaco, Bolívar",
         frase="Ya tenemos la ropita lista… ¡solo falta saber de qué color! Ven a descubrirlo con nosotros.", voto=True,
         regalo=PANALES, cierre="¡Te esperamos!", apertura="persiana", particulas="petalos", motivo="hoja", colores=["#e8dcc8", "#a9bcd3", "#e7b9bf"], pista="Toca para abrir",
         voladores=["mariposa"], fuentes=["Cormorant+Garamond:ital,wght@0,400;0,600;1,500", "Allura"],
         vars=tema("#faf7f0", "#efe9dc", "#4a4538", "#5f5a44", "#a39a7c", "#6f6749", '"Allura",cursive', '"Cormorant Garamond",serif',
                   "#5f5a44", claro("rgba(250,247,240,.95)"), "58px", "56px", "42px", "#e7b9bf")),

    base(slug="revelacion-abejitas", tarjeta="¿Qué será? Abejitas", categoria="Revelación de género", musica="abejitas", iconos="circulo",
         imagen=R + "IcYbAhu6kDlMI0_snhdGWkb0N_oSbDxYu_lOgCyk8nA/rs:fit:768:1344:0/raw:1/plain/abs://external/images/29e141a9-9d69-4253-9ca4-d372ead56b12",
         titulo="¿Qué será? · Revelación", eti="Revelación de género", nombre="¿Qué será?", subnombre="Familia Mejía Soto", evento="la revelación de nuestro bebé",
         fechaISO="2027-06-12T16:00:00-05:00", fechaTexto="Sábado 12 de junio", anioHora="2027 · 4:00 p. m.", fechaCorta="12 · 06 · 2027",
         lugar="Jardín La Colmena", direccion="Calle 30 # 14-22", ciudad="Neiva, Huila",
         frase="Zumba, zumba… ¿será abejito o abejita? ¡Ven a descubrirlo con nosotros! 🐝", voto=True,
         vestir={"lineas": [("Team abejito", "Ven de azul"), ("Team abejita", "Ven de rosa")], "colores": ["#9dc0e3", "#f2afc3", "#f4cd5c"]},
         regalo=PANALES, cierre="¡Te esperamos!", apertura="rasca", rascaMsg="¡Ven a descubrirlo con nosotros! 🐝", particulas="confeti", motivo="flor",
         colores=["#f4cd5c", "#9dc0e3", "#f2afc3", "#ffffff"], voladores=["abeja"], fuentes=["Chewy", NUNITO],
         vars=tema("#fffaf0", "#fff1c9", "#4a3d24", "#7a5a12", "#e3b23c", "#9a6f10", '"Chewy",cursive', '"Nunito",sans-serif',
                   "#7a5a12", claro("rgba(255,250,240,.95)"), "54px", "50px", "34px", "#f4cd5c")),

    # ============================== BAUTIZO ==============================
    base(slug="bautizo-lazo-perlas", tarjeta="Lazo de Perlas", categoria="Bautizo", musica="bautizo-capilla", iconos="linea",
         imagen=R + "C0CmbrGTn14RICYTWnaZYwtOouLklCyqKzRjER-ZZXw/rs:fit:768:1344:0/raw:1/plain/abs://external/images/ee28aa43-702b-4e6e-9d34-7f6f8162033e",
         titulo="Mi bautizo · Emilia", eti="Mi bautizo", nombre="Emilia", evento="mi bautizo",
         fechaISO="2027-02-13T10:00:00-05:00", fechaTexto="Sábado 13 de febrero", anioHora="2027 · 10:00 a. m.", fechaCorta="13 · 02 · 2027",
         lugar="Parroquia Santo Toribio", direccion="Calle del Curato", ciudad="Cartagena de Indias", titLugar="Ceremonia",
         lugar2=("Casa de los abuelos", "Barrio Manga, Calle 26 # 20-15", "Celebración"),
         padrinos=("Mis padrinos", "Andrés Gómez y Laura Pineda"),
         frase="Con un lazo de amor y fe, mis papás me presentan ante Dios. Me encantaría que me acompañes.",
         regalo=PRESENCIA, cierre="¡Te espero!", apertura="subir", particulas="estrellas", motivo="cruz", pista="Toca para abrir",
         fuentes=["Pinyon+Script", CORM],
         vars=tema("#fbf8f2", "#f5efe4", "#4a4234", "#6a5a3c", "#c2a878", "#8a6f40", '"Pinyon Script",cursive', '"Cormorant Garamond",serif',
                   "#6a5a3c", claro("rgba(251,248,242,.95)"), "66px", "64px", "44px", "#f0e2c4")),

    base(slug="bautizo-ovejita", tarjeta="Ovejita", categoria="Bautizo", musica="bautizo-nubes", iconos="suave",
         imagen=R + "BPXFcWQV4yzbB7AaXLHQbvNhBGFX3lqdIOLKPqA5VNI/rs:fit:768:1344:0/raw:1/plain/abs://external/images/026091ec-7c60-4bc1-a642-aa3e33a6ee46",
         titulo="Mi bautizo · Tomás", eti="Mi bautizo", nombre="Tomás", evento="mi bautizo",
         fechaISO="2027-03-06T11:00:00-05:00", fechaTexto="Sábado 6 de marzo", anioHora="2027 · 11:00 a. m.", fechaCorta="06 · 03 · 2027",
         lugar="Parroquia San Francisco", direccion="Carrera 9 # 13-40", ciudad="Tunja, Boyacá", titLugar="Ceremonia",
         lugar2=("Restaurante El Prado", "Calle 20 # 11-35", "Almuerzo"),
         padrinos=("Mis padrinos", "Felipe Rojas y Camila Durán"),
         frase="«El Señor es mi pastor, nada me faltará». Acompáñame el día que recibo el sacramento del bautismo.",
         regalo=PRESENCIA, cierre="¡Te espero!", apertura="iris", particulas="petalos", motivo="hoja", colores=["#ffffff", "#e9eee0", "#f1dfdc"], pista="Toca para abrir",
         fuentes=["Great+Vibes", "Lora:ital,wght@0,400;0,500;0,600;1,400"],
         vars=tema("#fbfaf5", "#eef1e6", "#3f4538", "#56663f", "#94a57e", "#5f7048", '"Great Vibes",cursive', '"Lora",serif',
                   "#56663f", claro("rgba(251,250,245,.95)"), "68px", "64px", "44px", "#ffffff")),

    base(slug="bautizo-arco-celeste", tarjeta="Arco Celeste", categoria="Bautizo", musica="comunion", iconos="arco",
         imagen=R + "5-HrWKtfqAt2EvwMWmtfSgSm1_GGFzgi3iWkf4DE68s/rs:fit:768:1344:0/raw:1/plain/abs://external/images/8de0849e-4f8a-4932-85f3-62b08fee34c3",
         titulo="Mi bautizo · Santiago", eti="Mi bautizo", nombre="Santiago", evento="mi bautizo",
         fechaISO="2027-04-17T10:30:00-05:00", fechaTexto="Sábado 17 de abril", anioHora="2027 · 10:30 a. m.", fechaCorta="17 · 04 · 2027",
         lugar="Catedral de San Jerónimo", direccion="Calle 27 con Carrera 3", ciudad="Montería, Córdoba", titLugar="Ceremonia",
         lugar2=("Club Campestre", "Vía a Planeta Rica, km 3", "Celebración"),
         padrinos=("Mis padrinos", "Juan David Correa y Paula Méndez"),
         frase="Bajo este arco de flores y fe, comienzo mi camino con Dios. ¡Acompáñame!",
         regalo=PRESENCIA, cierre="¡Te espero!", apertura="arco", particulas="estrellas", motivo="cruz", pista="Toca para abrir",
         fuentes=["Playfair+Display:ital,wght@0,400;0,500;1,400", "Alex+Brush"],
         vars=tema("#f8fafc", "#e6eef6", "#34445a", "#3d5f86", "#89a8c8", "#4f729a", '"Alex Brush",cursive', '"Playfair Display",serif',
                   "#3d5f86", claro("rgba(248,250,252,.0)"), "62px", "60px", "42px", "#ffffff")),

    # ============================== PRIMERA COMUNIÓN ==============================
    base(slug="comunion-nino-celeste", tarjeta="Niño Celeste", categoria="Primera comunión", musica="comunion", iconos="arco",
         imagen=R + "Y_CRsUusC2JrmA5AIZKkGnPZFhwtWZyyP6oqF2k8k88/rs:fit:768:1344:0/raw:1/plain/abs://external/images/ab76990b-2809-4262-90e7-c3bb3a48a19b",
         titulo="Mi primera comunión · Gabriel", eti="Mi primera comunión", nombre="Gabriel", evento="mi primera comunión",
         fechaISO="2027-05-29T10:00:00-05:00", fechaTexto="Sábado 29 de mayo", anioHora="2027 · 10:00 a. m.", fechaCorta="29 · 05 · 2027",
         lugar="Parroquia Cristo Rey", direccion="Carrera 15 # 20-30", ciudad="Sincelejo, Sucre", titLugar="Misa",
         lugar2=("Casa de la familia", "Calle 22 # 17-40", "Celebración"),
         frase="Con mucha alegría recibiré a Jesús por primera vez en mi corazón. ¡Acompáñame en este día tan especial!",
         regalo=PRESENCIA, cierre="¡Te espero!", apertura="puertas", particulas="estrellas", motivo="cruz", pista="Toca para abrir",
         fuentes=["Tangerine:wght@400;700", "Lora:ital,wght@0,400;0,500;0,600;1,400"],
         vars=tema("#f8fafc", "#e7eef6", "#34445a", "#3d5f86", "#89a8c8", "#4f729a", '"Tangerine",cursive', '"Lora",serif',
                   "#3d5f86", claro("rgba(248,250,252,.95)"), "80px", "78px", "56px", "#e9d59a")),

    base(slug="comunion-arco-salvia", tarjeta="Arco Salvia", categoria="Primera comunión", musica="bautizo-capilla", iconos="linea",
         imagen=R + "o1uZbk2rar6537_e74V_VKdDiSK8HXNHoGEJ4uLNnds/rs:fit:768:1344:0/raw:1/plain/abs://external/images/5ec3d165-82d8-4f14-9f1f-3b133bf7041c",
         titulo="Mi primera comunión · Mariana", eti="Mi primera comunión", nombre="Mariana", evento="mi primera comunión",
         fechaISO="2027-06-05T09:00:00-05:00", fechaTexto="Sábado 5 de junio", anioHora="2027 · 9:00 a. m.", fechaCorta="05 · 06 · 2027",
         lugar="Parroquia La Milagrosa", direccion="Calle 45 # 20-12", ciudad="Barranquilla, Atlántico", titLugar="Misa",
         lugar2=("Salón Olivo", "Carrera 52 # 76-20", "Celebración"),
         frase="«Yo soy el pan de vida». Hoy recibo a Jesús con el corazón lleno de alegría y quiero compartirlo contigo.",
         regalo=PRESENCIA, cierre="¡Te espero!", apertura="arco", particulas="petalos", motivo="hoja", colores=["#ffffff", "#e3e9da", "#f2ead8"], pista="Toca para abrir",
         fuentes=["Italianno", CORM],
         vars={**tema("#fbfaf5", "#eef0e6", "#3e4237", "#56613f", "#a3ae8a", "#667248", '"Italianno",cursive', '"Cormorant Garamond",serif',
                   "#56613f", claro("rgba(251,250,245,.0)"), "70px", "68px", "48px", "#e9d59a"), "texto-abajo": "calc(38vh)", "margen-texto": "78px"}),

    base(slug="comunion-paloma", tarjeta="Paloma de Paz", categoria="Primera comunión", musica="luna", iconos="circulo",
         imagen=R + "tzj3DqLzYkILz0yE7WLbxH2NkVH0lCYpB2kOpadt39w/rs:fit:768:1344:0/raw:1/plain/abs://external/images/f82a5cd2-b2e4-489d-868f-0e5494902372",
         titulo="Mi primera comunión · Sebastián", eti="Mi primera comunión", nombre="Sebastián", evento="mi primera comunión",
         fechaISO="2027-06-19T10:00:00-05:00", fechaTexto="Sábado 19 de junio", anioHora="2027 · 10:00 a. m.", fechaCorta="19 · 06 · 2027",
         lugar="Parroquia San Pedro Claver", direccion="Plaza de San Pedro Claver", ciudad="Cartagena de Indias", titLugar="Misa",
         lugar2=("Hotel Almirante", "Avenida San Martín # 6-153", "Celebración"),
         frase="Como la paloma que trae paz, hoy recibo a Jesús en mi corazón. Me encantaría que estés conmigo.",
         regalo=PRESENCIA, cierre="¡Te espero!", apertura="nubes", particulas="estrellas", motivo="cruz", pista="Toca para abrir",
         fuentes=["Pinyon+Script", "Libre+Baskerville:ital@0;1"],
         vars=tema("#f8f9fb", "#e8edf5", "#363f52", "#40557e", "#8b9fc2", "#51678f", '"Pinyon Script",cursive', '"Libre Baskerville",serif',
                   "#40557e", claro("rgba(248,249,251,.95)"), "62px", "60px", "40px", "#e9d59a")),

    base(slug="comunion-velo-rosas", tarjeta="Velo y Rosas", categoria="Primera comunión", musica="coquette", iconos="suave",
         imagen=R + "wH2xAF1n89_piG8Dck1Cfpg6O73gs0NQeYv2aLxl2UM/rs:fit:768:1344:0/raw:1/plain/abs://external/images/afd12a44-d9f6-4202-b554-c964ad34f29f",
         titulo="Mi primera comunión · Antonia", eti="Mi primera comunión", nombre="Antonia", evento="mi primera comunión",
         fechaISO="2027-07-03T09:30:00-05:00", fechaTexto="Sábado 3 de julio", anioHora="2027 · 9:30 a. m.", fechaCorta="03 · 07 · 2027",
         lugar="Parroquia Nuestra Señora de Fátima", direccion="Calle 33 # 26-10", ciudad="Bucaramanga, Santander", titLugar="Misa",
         lugar2=("Casa Rosada", "Carrera 29 # 41-12", "Celebración"),
         frase="Con mi velo, mis rosas y mucha fe, recibiré a Jesús por primera vez. ¡Acompáñame en este día!",
         regalo=PRESENCIA, cierre="¡Te espero!", apertura="libro", particulas="petalos", motivo="flor", colores=["#f3c9cc", "#fbe6e4", "#ffffff"], pista="Toca para abrir",
         fuentes=["Great+Vibes", "Lora:ital,wght@0,400;0,500;0,600;1,400"],
         vars=tema("#fdf8f3", "#fbeae6", "#4e3e3a", "#9a5a60", "#d49aa0", "#9a5a60", '"Great Vibes",cursive', '"Lora",serif',
                   "#9a5a60", claro("rgba(253,248,243,.95)"), "68px", "64px", "44px", "#f3c9cc")),
]
